<?php

namespace AppBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{


    //a) Selecciona todos los clientes que tengan un pedido de valor superior a 30€

    public function supTreinta()
    {
        return $this->createQueryBuilder('b')
            ->addOrderBy('b.createdAt', 'DESC')
            ->addSelect('b.precio'>30)
            ->getQuery()
            ->execute()
            ;
    }













}
